### ISSUE TITLE
warnings from rspec

### ISSUE THREAD

**Issue by mdave16** [floraison/et-orbi#10]
I am using `rufus`, and when i run `rspec` with tests, I get the following warnings:

```
/Users/me/.rvm/gems/ruby-2.4.2/gems/et-orbi-1.0.5/lib/et-orbi.rb:608: warning: assigned but unused variable - tu
/Users/me/.rvm/gems/ruby-2.4.2/gems/et-orbi-1.0.5/lib/et-orbi.rb:151: warning: instance variable @local_tzone_loaded_at not initialized
/Users/me/.rvm/gems/ruby-2.4.2/gems/et-orbi-1.0.5/lib/et-orbi.rb:153: warning: instance variable @local_tzone_tz not initialized
```

I imagine they are easy fixes, and just leftover from some change or another.

**Comment by mdave16** [comment]
noticed I was out of date, so updated to `1.0.8`;

`/Users/me/.rvm/gems/ruby-2.4.2/gems/et-orbi-1.0.8/lib/et-orbi.rb:682: warning: assigned but unused variable - tu
/Users/me/.rvm/gems/ruby-2.4.2/gems/et-orbi-1.0.8/lib/et-orbi.rb:163: warning: instance variable @local_tzone_loaded_at not initialized
/Users/me/.rvm/gems/ruby-2.4.2/gems/et-orbi-1.0.8/lib/et-orbi.rb:165: warning: instance variable @local_tzone_tz not initialized`

same issues, but different lines. I know sometimes warnings can be ignored, but it's best practice not to.

**Comment by jmettraux** [comment]
Many thanks!

**Comment by jmettraux** [comment]
1.0.9 has been pushed to RubyGems and it includes the fix.

Thanks again.
