### ISSUE TITLE
@_os_zone not initialized

### ISSUE THREAD

**Issue by itsjamie** [floraison/et-orbi#13]
Hello, I'm getting this warning printed when running a test suite.

`gems/et-orbi-1.1.3/lib/et-orbi.rb:675: warning: instance variable @_os_zone not initialized`

The code imports rufus-scheduler and uses it like:

```ruby
@@scheduler = LazyObject.new { Rufus::Scheduler.new }
def scheduler; @@scheduler; end
```

What is missing to be able to not have this warning? Thanks!

**Comment by jmettraux** [comment]
Hello,

thanks for reporting this warning. I have silenced it along with two other warnings, https://github.com/floraison/et-orbi/commit/6d46c71749668e51fcab1eeb8068e24b75e163e5 and https://github.com/floraison/et-orbi/commit/2165275f663f2006c0b219e23bafe6c0764f6b89

Please try again with et-orbi 1.1.4, I've just [released it](https://rubygems.org/gems/et-orbi).

If there is anything else, please tell me.

Best regards.

**Comment by jmettraux** [comment]
No news. Closing.

**Comment by itsjamie** [comment]
Hello! I just wanted to say, I meant to thank you. I updated this and it silenced the warnings. The tests are much clearer now!

**Comment by jmettraux** [comment]
@itsjamie Thanks a lot!
