### ISSUE TITLE
Cannot call add or subtract ActiveSupport::Duration to EoTime instance

### ISSUE THREAD

**Issue by rangerscience** [floraison/et-orbi#40]
Simple:
```
> Fugit.parse("every day at 9").next_time + 1.hour
`<main>': Cannot call add or subtract ActiveSupport::Duration to EoTime instance (ArgumentError)
```

This makes sense (Rails is doing it's own shenanigans with `Time` and all that), and it's easy to resolve:

```
> Fugit.parse("every day at 9").next_time.to_local_time + 1.hour
=> 2024-12-04 05:00:00 -0500
```

but now we've lost the nice bit that Et Orbi adds :)

PS - I'll see if I can carve out some time to dig in and submit a PR :)

**Comment by jmettraux** [comment]
@rangerscience Thanks!

> PS - I'll see if I can carve out some time to dig in and submit a PR :)

Let me try it first, I have a few hours before me.

**Comment by jmettraux** [comment]
@rangerscience would the above commit match your needs?

**Comment by rangerscience** [comment]
At a glance, it looks like it would! I like the idea of handling the general case of "adding a number" - that's a good abstraction.

**Comment by jmettraux** [comment]
> PS - I'm not actually sure how to go about checking this out live, so "at a glance" = "reading the code", rather than running it :)

You could point your project's Gemfile to the current et-orbi main branch instead of the released gem and try.
